NumPy Retail Analytics Assignment
Business Scenario
You are working as a Data Analyst for SmartMart Retail Stores. The company operates five stores in different cities and sells six major product categories.

Management wants to analyze sales performance, expenses, profits, targets, discounts, inventory, and store-level performance using NumPy.

You are provided with two main NumPy arrays:

sales_data — monthly sales revenue generated by each store for different product categories.
cost_data — total cost incurred by each store for the same product categories.

Part 1: Dataset Creation

In [2]:
import numpy as np

# Store names
stores = np.array([
    "Bengaluru",
    "Hyderabad",
    "Chennai",
    "Mumbai",
    "Pune"
])

# Product categories
categories = np.array([
    "Electronics",
    "Groceries",
    "Clothing",
    "Furniture",
    "Beauty",
    "Sports"
])

# Sales revenue in rupees
# Rows represent stores
# Columns represent product categories

sales_data = np.array([
    [850000, 420000, 310000, 275000, 190000, 225000],
    [780000, 460000, 295000, 310000, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, 510000, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, 175000, 205000]
])

# Cost incurred in rupees
# Rows represent stores
# Columns represent product categories

cost_data = np.array([
    [640000, 315000, 220000, 205000, 125000, 160000],
    [590000, 350000, 210000, 225000, 140000, 170000],
    [700000, 295000, 245000, 195000, 120000, 155000],
    [790000, 390000, 265000, 250000, 165000, 205000],
    [530000, 310000, 205000, 170000, 115000, 145000]
])

print("Stores:")
print(stores)

print("\nProduct Categories:")
print(categories)

print("\nSales Data:")
print(sales_data)

print("\nCost Data:")
print(cost_data)

Stores:
['Bengaluru' 'Hyderabad' 'Chennai' 'Mumbai' 'Pune']

Product Categories:
['Electronics' 'Groceries' 'Clothing' 'Furniture' 'Beauty' 'Sports']

Sales Data:
[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]]

Cost Data:
[[640000 315000 220000 205000 125000 160000]
 [590000 350000 210000 225000 140000 170000]
 [700000 295000 245000 195000 120000 155000]
 [790000 390000 265000 250000 165000 205000]
 [530000 310000 205000 170000 115000 145000]]


Part 2: Basic Array Understanding

In [ ]:
# Question 1: Array Dimensions
# The finance manager wants to confirm how many stores and product categories are present in the data.

# Write NumPy code to display:

# Number of dimensions in sales_data
# Shape of sales_data
# Total number of values
# Data type of the array
# Memory occupied by the array
print("dimension:", np.ndim(sales_data))
print("shape: " ,np.shape(sales_data))
print("values: ",np.size(sales_data))
print("data type: ",sales_data.dtype)
print("memory: ",sales_data.itemsize)



dimension: 2
shape:  (5, 6)
values:  30
data type:  int64
memory:  8


In [ ]:
# Question 2: Store and Category Count
# Calculate the following:

# Total number of stores
# Total number of product categories
# Total number of store-category combinations

print("total number of stores: ", np.size(stores))
print("total number of product categories: ",np.size(categories))
print("total number of store-category combinations: ",np.size(stores)*np.size(categories))

total number of stores:  5
total number of product categories:  6
total number of store-category combinations:  30


In [ ]:
# Question 3: Sales Data Type Conversion
# The reporting application requires sales values in floating-point format.

# Convert sales_data into:

# float32
# float64
# Compare the memory used by both arrays.
sales_data_float32 = np.array(sales_data, dtype=np.float32)
sales_data_float64 = np.array(sales_data, dtype=np.float64)
print(sales_data_float32.dtype)
print(sales_data_float64.dtype)
print(sales_data_float32.itemsize)
print(sales_data_float64.itemsize)
print("memory float32: ",sales_data_float32.nbytes)
print("memory float64:",sales_data_float64.nbytes)

float32
float64
4
8
memory float32:  120
memory float64: 240


In [ ]:
# Part 3: Indexing and Data Extraction
# Question 4: Bengaluru Store Analysis
# The Bengaluru regional manager wants to review sales for all product categories.
# Extract and display the complete sales row for Bengaluru.
print(sales_data[0])


[850000 420000 310000 275000 190000 225000]


In [ ]:
# Question 5: Mumbai Cost Analysis
# Extract the total cost incurred by the Mumbai store for all product categories.
print(cost_data[3].sum())

2065000


In [ ]:
# Question 6: Electronics Sales Across Stores
# The electronics department wants to compare its sales performance across all five stores.

# Extract the Electronics sales column from sales_data.
print(sales_data[:,0])

[ 850000  780000  920000 1050000  690000]


In [ ]:
# Question 7: Clothing Cost Across Stores
# Extract the Clothing cost for every store from cost_data.
print(cost_data[:,2])

[220000 210000 245000 265000 205000]


In [ ]:
# Question 8: Hyderabad Furniture Performance
# Find the following for Hyderabad:

# Furniture sales
# Furniture cost
# Furniture profit

print("furniture sales: ",sales_data[1:,3])
print("furniture cost: ",cost_data[1:,3])
print("furniture profit: ", sales_data[1:,3] - cost_data[1:,3])

furniture sales:  [310000 260000 345000 225000]
furniture cost:  [225000 195000 250000 170000]
furniture profit:  [85000 65000 95000 55000]


In [ ]:
# Question 9: Chennai Category Range
# Extract Chennai’s sales for the following categories:

# Groceries
# Clothing
# Furniture
# Use array slicing.
print(sales_data[2, 1:4])

[390000 340000 260000]


In [ ]:
# Question 10: Selected Store Analysis
# Extract sales data for:
# Bengaluru
# Chennai
# Pune
# Include only:
# Electronics
# Clothing
# Beauty
# Use advanced indexing.

print(sales_data[[0,2,4]][:,[0,2,4]])

[[850000 310000 190000]
 [920000 340000 185000]
 [690000 280000 175000]]


In [ ]:
# Part 4: Sales Aggregation
# Question 11: Company-Wide Sales
# Calculate the total sales revenue generated by all stores and all categories.
print(sales_data.sum())

11675000


In [ ]:
# Question 12: Store-Wise Sales
# Calculate total sales revenue for each store.
# Display the result together with the store names.
print("bengalore :",sales_data[0].sum())
print("hyderabad :", sales_data[1].sum())
print("chennai :", sales_data[2].sum())
print("mumbai :",sales_data[3].sum())
print("pune :" , sales_data[4].sum())

bengalore : 2270000
hyderabad : 2295000
chennai : 2310000
mumbai : 2820000
pune : 1980000


In [ ]:
# Question 13: Category-Wise Sales
# Calculate total sales for each product category across all stores.

# Display each category name with its total sales.
print("electronics :", sales_data[:, 0].sum())
print("groceries :", sales_data[:, 1].sum())
print("clothing :", sales_data[:,2].sum())
print("furniture :",sales_data[:,3].sum())
print("beauty :", sales_data[:,4].sum())
print("sports :",sales_data[:,5].sum())

electronics : 4290000
groceries : 2185000
clothing : 1600000
furniture : 1415000
beauty : 1010000
sports : 1175000


In [ ]:
# Question 14: Average Sales Per Store
# Calculate the average sales generated by each store across all six product categories.
print("bengalore :",sales_data[0].sum()/sales_data.shape[1])
print("hyderabad :", sales_data[1].sum()/sales_data.shape[1])
print("chennai :", sales_data[2].sum()/sales_data.shape[1])
print("mumbai :",sales_data[3].sum()/sales_data.shape[1])
print("pune :" , sales_data[4].sum()/sales_data.shape[1])


bengalore : 378333.3333333333
hyderabad : 382500.0
chennai : 385000.0
mumbai : 470000.0
pune : 330000.0


In [ ]:
# Question 15: Average Sales Per Category
# Calculate the average sales of each product category across the five stores.
print("electronics :", sales_data[:, 0].sum()/sales_data.shape[0])
print("groceries :", sales_data[:, 1].sum()/sales_data.shape[0])
print("clothing :", sales_data[:,2].sum()/sales_data.shape[0])
print("furniture :",sales_data[:,3].sum()/sales_data.shape[0])
print("beauty :", sales_data[:,4].sum()/sales_data.shape[0])
print("sports :",sales_data[:,5].sum()/sales_data.shape[0])

electronics : 858000.0
groceries : 437000.0
clothing : 320000.0
furniture : 283000.0
beauty : 202000.0
sports : 235000.0


In [ ]:
# Question 16: Highest-Selling Store
# Identify:

# Index of the store with the highest total sales
# Name of the store
# Total sales generated by that store
# Use np.argmax().

value = np.argmax(sales_data.sum(axis=1))
print(value)
print(stores[value])
print(sales_data[value].sum())

3
Mumbai
2820000


In [ ]:
# Question 17: Lowest-Selling Store
# Identify the store with the lowest overall sales.

# Use np.argmin().
value = np.argmin(sales_data.sum(axis=1))
print(value)
print(stores[value])
print(sales_data[value].sum())

4
Pune
1980000


In [ ]:
# Question 18: Highest-Selling Category
# Find the product category that generated the highest total sales across the company.
index =np.argmax(sales_data.sum(axis =0))
print(index)
print(categories[index])
print(sales_data[:,index].sum())

0
Electronics
4290000


In [ ]:
# Question 19: Lowest-Selling Category
# Find the product category with the lowest total sales across all stores
index = np.argmin(sales_data.sum(axis =0))
print(index)
print(categories[index])
print(sales_data[:,index].sum())

4
Beauty
1010000


In [ ]:
# Part 5: Cost Analysis
# Question 20: Total Company Cost
# Calculate the total cost incurred by SmartMart across all stores and product categories.
print(cost_data.sum())


8600000


In [ ]:
# Question 21: Store-Wise Cost
# Calculate the total cost incurred by each store.
print("bengalore :" ,cost_data[0].sum())
print("hyderbad :", cost_data[1].sum())
print("chennai :", cost_data[2].sum())
print("mumbai :",cost_data[3].sum())
print("pune :",cost_data[4].sum())

bengalore : 1665000
hyderbad : 1685000
chennai : 1710000
mumbai : 2065000
pune : 1475000


In [ ]:
# Question 22: Category-Wise Cost
# Calculate the total cost incurred for each product category across all stores.

print("electronics :", cost_data[:, 0].sum())
print("groceries :", cost_data[:, 1].sum())
print("clothing :", cost_data[:,2].sum())
print("furniture :",cost_data[:,3].sum())
print("beauty :", cost_data[:,4].sum())
print("sports :",cost_data[:,5].sum())

electronics : 3250000
groceries : 1660000
clothing : 1145000
furniture : 1045000
beauty : 665000
sports : 835000


In [ ]:
# Question 23: Most Expensive Store
# Identify the store with the highest total operating cost.

Expensive =np.argmax(cost_data.sum(axis=1))
print(stores[Expensive])


Mumbai


In [ ]:
# Question 24: Lowest-Cost Store
# Identify the store with the lowest total cost.
min = np.argmin(cost_data.sum(axis=1))
print(stores[min])

Pune


In [ ]:
# Question 25: Most Expensive Product Category
# Determine which product category has the highest total cost across all stores.
index =np.argmax(cost_data.sum(axis=0))
print(categories[index])


Electronics


In [3]:
# Part 6: Profit Analysis Using Two Arrays
# Question 26: Profit Matrix
# Calculate the profit generated for every store and product category.

# Use:

# profit_data = sales_data - cost_data
# Display the complete profit matrix.

profit_data = sales_data - cost_data
print(profit_data)

[[210000 105000  90000  70000  65000  65000]
 [190000 110000  85000  85000  70000  70000]
 [220000  95000  95000  65000  65000  60000]
 [260000 120000 110000  95000  85000  85000]
 [160000  95000  75000  55000  60000  60000]]


In [ ]:
# Question 27: Store-Wise Profit
# Calculate the total profit generated by each store.
print("bengalore :",profit_data[0].sum())
print("hyderabad :", profit_data[1].sum())
print("chennai :", profit_data[2].sum())
print("mumbai :",profit_data[3].sum())
print("pune :",profit_data[4].sum())

bengalore : 605000
hyderabad : 610000
chennai : 600000
mumbai : 755000
pune : 505000


In [ ]:
# Question 28: Category-Wise Profit
# Calculate the total profit generated by each product category.
print("electronics :", profit_data[:, 0].sum())
print("groceries :", profit_data[:, 1].sum())
print("clothing :", profit_data[:,2].sum())
print("furniture :",profit_data[:,3].sum())
print("beauty :", profit_data[:,4].sum())
print("sports :",profit_data[:,5].sum())


electronics : 1040000
groceries : 525000
clothing : 455000
furniture : 370000
beauty : 345000
sports : 340000


In [ ]:
# Question 29: Most Profitable Store
# Identify the store that generated the highest total profit.

# Display:

# Store name
# Total sales
# Total cost
# Total profit

index=np.argmax(profit_data.sum(axis=1))
print("store;", stores[index])
print("total sales:",sales_data[index].sum())
print(cost_data[index].sum())
print(sales_data[index].sum()-cost_data[index].sum())

store; Mumbai
total sales: 2820000
2065000
755000


In [ ]:
# Question 30: Least Profitable Store
# Identify the store that generated the lowest total profit.

least = np.argmin(profit_data.sum(axis=1))
print("store: ", stores[least])

store:  Pune


In [ ]:
# Question 31: Most Profitable Category
# Find the category with the highest total profit across all stores.
index = np.argmax(profit_data.sum(axis=0))
print("category: ",categories[index])

category:  Electronics


In [ ]:
# Question 32: Least Profitable Category
# Find the category with the lowest total profit.

lesat=np.argmin(profit_data.sum(axis=0))
print("category: ",categories[lesat])

category:  Sports


In [ ]:
# Question 33: Maximum Individual Profit
# Find the highest profit generated by any single store-category combination.

# Display:

# Profit amount
# Store name
# Product category
# Use np.unravel_index().
index= np.argmax(profit_data)
r , c = np.unravel_index(index, profit_data.shape)
print("profit:",profit_data[r,c])
print("store:",stores[r])
print("category:", categories[c])


profit: 260000
store: Mumbai
category: Electronics


In [ ]:
# Question 34: Minimum Individual Profit
# Find the smallest profit generated by a store-category combination.

# Display the corresponding store and category.
index= np.argmin(profit_data)
r,c = np.unravel_index(index, profit_data.shape)
print("profit:",profit_data[r,c])
print("store:",stores[r])
print("category:", categories[c])

profit: 55000
store: Pune
category: Furniture


In [34]:
# Part 7: Profit Margin Analysis
# Question 35: Profit Margin Matrix
# Calculate the profit margin percentage for every store-category combination.

# Use:

# profit_margin = (profit_data / sales_data) * 100
# Round the result to two decimal places.
profit_margin = (profit_data / sales_data) * 100
print(profit_margin.round(2))

[[24.71 25.   29.03 25.45 34.21 28.89]
 [24.36 23.91 28.81 27.42 33.33 29.17]
 [23.91 24.36 27.94 25.   35.14 27.91]
 [24.76 23.53 29.33 27.54 34.   29.31]
 [23.19 23.46 26.79 24.44 34.29 29.27]]


In [9]:
# Question 36: Store-Wise Profit Margin
# Calculate the overall profit margin percentage for each store using:

# Store Profit Margin =
# Total Store Profit / Total Store Sales × 100
store_profit_margin = (profit_data.sum(axis=1)/sales_data.sum(axis=1))*100
print(store_profit_margin.round(2))


[26.65 26.58 25.97 26.77 25.51]


In [14]:
# Question 37: Category-Wise Profit Margin
# Calculate the overall profit margin percentage for each product category.

category_profit_margin=(profit_data.sum(axis=0)/sales_data.sum(axis=0))*100
print(category_profit_margin.round(2))

[24.24 24.03 28.44 26.15 34.16 28.94]


In [18]:
# Question 38: Best Store by Profit Margin
# Identify the store with the highest overall profit margin.
index = np.argmax(store_profit_margin)
print("store:",stores[index])

store: Mumbai


In [23]:
# Question 39: Best Category by Profit Margin
# Identify the product category with the highest profit margin.
index=np.argmax(category_profit_margin)
print("category:",categories[index])

category: Beauty


In [36]:
# Question 40: Low-Margin Transactions
# Management considers a profit margin below 22% to be weak.

# Find all store-category combinations where the profit margin is below 22%.

# Display:

# Store
# Category
# Sales
# Cost
# Profit
# Profit margin
# Use Boolean indexing.
low = profit_margin < 22
r,c = np.where(low)
for r,c in zip(r,c):
  print("store:",stores[r])
  print("category:",categories[c])
  print("sales:",sales_data[r,c])
  print("cost:",cost_data[r,c])
  print("profit:",profit_data[r,c])
  print("profit margin:",profit_margin[r,c])

In [39]:
# Part 8: Boolean Filtering
# Question 41: High Sales Values
# Find all sales values greater than ₹5,00,000.

high=sales_data[sales_data> 500000]
print(high)

[ 850000  780000  920000 1050000  510000  690000]


In [44]:
# Question 42: Low Sales Values
# Find all sales values below ₹2,00,000.
low = sales_data[sales_data<200000]
print(low)

[190000 185000 175000]


In [47]:
# Question 43: High Profit Values
# Find all store-category combinations where profit is greater than ₹1,50,000.

high =profit_data[profit_data>150000]
print(high)

[210000 190000 220000 260000 160000]


In [51]:
# Question 44: Moderate Sales Range
# Find sales values between ₹2,50,000 and ₹5,00,000.
# Use np.logical_and().

moderate=sales_data[np.logical_and(sales_data>= 250000,sales_data<=500000) ]
print(moderate)

[420000 310000 275000 460000 295000 310000 390000 340000 260000 375000
 345000 250000 290000 405000 280000]


In [53]:
# Question 45: Premium Performance
# A store-category combination is considered premium when:

# Sales are greater than ₹5,00,000
# Profit is greater than ₹1,50,000
# Find all premium-performing combinations.
premium=profit_data[np.logical_and(sales_data>500000,profit_data>150000)]
print(premium)

[210000 190000 220000 260000 160000]
