NumPy Retail Analytics Assignment
Business Scenario
You are working as a Data Analyst for SmartMart Retail Stores. The company operates five stores in different cities and sells six major product categories.

Management wants to analyze sales performance, expenses, profits, targets, discounts, inventory, and store-level performance using NumPy.

You are provided with two main NumPy arrays:

sales_data — monthly sales revenue generated by each store for different product categories.
cost_data — total cost incurred by each store for the same product categories.

Part 1: Dataset Creation

In [1]:
import numpy as np

# Store names
stores = np.array([
    "Bengaluru",
    "Hyderabad",
    "Chennai",
    "Mumbai",
    "Pune"
])

# Product categories
categories = np.array([
    "Electronics",
    "Groceries",
    "Clothing",
    "Furniture",
    "Beauty",
    "Sports"
])

# Sales revenue in rupees
# Rows represent stores
# Columns represent product categories

sales_data = np.array([
    [850000, 420000, 310000, 275000, 190000, 225000],
    [780000, 460000, 295000, 310000, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, 510000, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, 175000, 205000]
])

# Cost incurred in rupees
# Rows represent stores
# Columns represent product categories

cost_data = np.array([
    [640000, 315000, 220000, 205000, 125000, 160000],
    [590000, 350000, 210000, 225000, 140000, 170000],
    [700000, 295000, 245000, 195000, 120000, 155000],
    [790000, 390000, 265000, 250000, 165000, 205000],
    [530000, 310000, 205000, 170000, 115000, 145000]
])

print("Stores:")
print(stores)

print("\nProduct Categories:")
print(categories)

print("\nSales Data:")
print(sales_data)

print("\nCost Data:")
print(cost_data)

Stores:
['Bengaluru' 'Hyderabad' 'Chennai' 'Mumbai' 'Pune']

Product Categories:
['Electronics' 'Groceries' 'Clothing' 'Furniture' 'Beauty' 'Sports']

Sales Data:
[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]]

Cost Data:
[[640000 315000 220000 205000 125000 160000]
 [590000 350000 210000 225000 140000 170000]
 [700000 295000 245000 195000 120000 155000]
 [790000 390000 265000 250000 165000 205000]
 [530000 310000 205000 170000 115000 145000]]


Part 2: Basic Array Understanding

In [ ]:
# Question 1: Array Dimensions
# The finance manager wants to confirm how many stores and product categories are present in the data.

# Write NumPy code to display:

# Number of dimensions in sales_data
# Shape of sales_data
# Total number of values
# Data type of the array
# Memory occupied by the array
print("dimension:", np.ndim(sales_data))
print("shape: " ,np.shape(sales_data))
print("values: ",np.size(sales_data))
print("data type: ",sales_data.dtype)
print("memory: ",sales_data.itemsize)



dimension: 2
shape:  (5, 6)
values:  30
data type:  int64
memory:  8


In [ ]:
# Question 2: Store and Category Count
# Calculate the following:

# Total number of stores
# Total number of product categories
# Total number of store-category combinations

print("total number of stores: ", np.size(stores))
print("total number of product categories: ",np.size(categories))
print("total number of store-category combinations: ",np.size(stores)*np.size(categories))

total number of stores:  5
total number of product categories:  6
total number of store-category combinations:  30


In [ ]:
# Question 3: Sales Data Type Conversion
# The reporting application requires sales values in floating-point format.

# Convert sales_data into:

# float32
# float64
# Compare the memory used by both arrays.
sales_data_float32 = np.array(sales_data, dtype=np.float32)
sales_data_float64 = np.array(sales_data, dtype=np.float64)
print(sales_data_float32.dtype)
print(sales_data_float64.dtype)
print(sales_data_float32.itemsize)
print(sales_data_float64.itemsize)
print("memory float32: ",sales_data_float32.nbytes)
print("memory float64:",sales_data_float64.nbytes)

float32
float64
4
8
memory float32:  120
memory float64: 240


In [ ]:
# Part 3: Indexing and Data Extraction
# Question 4: Bengaluru Store Analysis
# The Bengaluru regional manager wants to review sales for all product categories.
# Extract and display the complete sales row for Bengaluru.
print(sales_data[0])


[850000 420000 310000 275000 190000 225000]


In [ ]:
# Question 5: Mumbai Cost Analysis
# Extract the total cost incurred by the Mumbai store for all product categories.
print(cost_data[3].sum())

2065000


In [ ]:
# Question 6: Electronics Sales Across Stores
# The electronics department wants to compare its sales performance across all five stores.

# Extract the Electronics sales column from sales_data.
print(sales_data[:,0])

[ 850000  780000  920000 1050000  690000]


In [ ]:
# Question 7: Clothing Cost Across Stores
# Extract the Clothing cost for every store from cost_data.
print(cost_data[:,2])

[220000 210000 245000 265000 205000]


In [ ]:
# Question 8: Hyderabad Furniture Performance
# Find the following for Hyderabad:

# Furniture sales
# Furniture cost
# Furniture profit

print("furniture sales: ",sales_data[1:,3])
print("furniture cost: ",cost_data[1:,3])
print("furniture profit: ", sales_data[1:,3] - cost_data[1:,3])

furniture sales:  [310000 260000 345000 225000]
furniture cost:  [225000 195000 250000 170000]
furniture profit:  [85000 65000 95000 55000]


In [ ]:
# Question 9: Chennai Category Range
# Extract Chennai’s sales for the following categories:

# Groceries
# Clothing
# Furniture
# Use array slicing.
print(sales_data[2, 1:4])

[390000 340000 260000]


In [ ]:
# Question 10: Selected Store Analysis
# Extract sales data for:
# Bengaluru
# Chennai
# Pune
# Include only:
# Electronics
# Clothing
# Beauty
# Use advanced indexing.

print(sales_data[[0,2,4]][:,[0,2,4]])

[[850000 310000 190000]
 [920000 340000 185000]
 [690000 280000 175000]]


In [ ]:
# Part 4: Sales Aggregation
# Question 11: Company-Wide Sales
# Calculate the total sales revenue generated by all stores and all categories.
print(sales_data.sum())

11675000


In [ ]:
# Question 12: Store-Wise Sales
# Calculate total sales revenue for each store.
# Display the result together with the store names.
print("bengalore :",sales_data[0].sum())
print("hyderabad :", sales_data[1].sum())
print("chennai :", sales_data[2].sum())
print("mumbai :",sales_data[3].sum())
print("pune :" , sales_data[4].sum())

bengalore : 2270000
hyderabad : 2295000
chennai : 2310000
mumbai : 2820000
pune : 1980000


In [ ]:
# Question 13: Category-Wise Sales
# Calculate total sales for each product category across all stores.

# Display each category name with its total sales.
print("electronics :", sales_data[:, 0].sum())
print("groceries :", sales_data[:, 1].sum())
print("clothing :", sales_data[:,2].sum())
print("furniture :",sales_data[:,3].sum())
print("beauty :", sales_data[:,4].sum())
print("sports :",sales_data[:,5].sum())

electronics : 4290000
groceries : 2185000
clothing : 1600000
furniture : 1415000
beauty : 1010000
sports : 1175000


In [ ]:
# Question 14: Average Sales Per Store
# Calculate the average sales generated by each store across all six product categories.
print("bengalore :",sales_data[0].sum()/sales_data.shape[1])
print("hyderabad :", sales_data[1].sum()/sales_data.shape[1])
print("chennai :", sales_data[2].sum()/sales_data.shape[1])
print("mumbai :",sales_data[3].sum()/sales_data.shape[1])
print("pune :" , sales_data[4].sum()/sales_data.shape[1])


bengalore : 378333.3333333333
hyderabad : 382500.0
chennai : 385000.0
mumbai : 470000.0
pune : 330000.0


In [ ]:
# Question 15: Average Sales Per Category
# Calculate the average sales of each product category across the five stores.
print("electronics :", sales_data[:, 0].sum()/sales_data.shape[0])
print("groceries :", sales_data[:, 1].sum()/sales_data.shape[0])
print("clothing :", sales_data[:,2].sum()/sales_data.shape[0])
print("furniture :",sales_data[:,3].sum()/sales_data.shape[0])
print("beauty :", sales_data[:,4].sum()/sales_data.shape[0])
print("sports :",sales_data[:,5].sum()/sales_data.shape[0])

electronics : 858000.0
groceries : 437000.0
clothing : 320000.0
furniture : 283000.0
beauty : 202000.0
sports : 235000.0


In [ ]:
# Question 16: Highest-Selling Store
# Identify:

# Index of the store with the highest total sales
# Name of the store
# Total sales generated by that store
# Use np.argmax().

value = np.argmax(sales_data.sum(axis=1))
print(value)
print(stores[value])
print(sales_data[value].sum())

3
Mumbai
2820000


In [ ]:
# Question 17: Lowest-Selling Store
# Identify the store with the lowest overall sales.

# Use np.argmin().
value = np.argmin(sales_data.sum(axis=1))
print(value)
print(stores[value])
print(sales_data[value].sum())

4
Pune
1980000


In [ ]:
# Question 18: Highest-Selling Category
# Find the product category that generated the highest total sales across the company.
index =np.argmax(sales_data.sum(axis =0))
print(index)
print(categories[index])
print(sales_data[:,index].sum())

0
Electronics
4290000


In [ ]:
# Question 19: Lowest-Selling Category
# Find the product category with the lowest total sales across all stores
index = np.argmin(sales_data.sum(axis =0))
print(index)
print(categories[index])
print(sales_data[:,index].sum())

4
Beauty
1010000


In [ ]:
# Part 5: Cost Analysis
# Question 20: Total Company Cost
# Calculate the total cost incurred by SmartMart across all stores and product categories.
print(cost_data.sum())


8600000


In [ ]:
# Question 21: Store-Wise Cost
# Calculate the total cost incurred by each store.
print("bengalore :" ,cost_data[0].sum())
print("hyderbad :", cost_data[1].sum())
print("chennai :", cost_data[2].sum())
print("mumbai :",cost_data[3].sum())
print("pune :",cost_data[4].sum())

bengalore : 1665000
hyderbad : 1685000
chennai : 1710000
mumbai : 2065000
pune : 1475000


In [ ]:
# Question 22: Category-Wise Cost
# Calculate the total cost incurred for each product category across all stores.

print("electronics :", cost_data[:, 0].sum())
print("groceries :", cost_data[:, 1].sum())
print("clothing :", cost_data[:,2].sum())
print("furniture :",cost_data[:,3].sum())
print("beauty :", cost_data[:,4].sum())
print("sports :",cost_data[:,5].sum())

electronics : 3250000
groceries : 1660000
clothing : 1145000
furniture : 1045000
beauty : 665000
sports : 835000


In [ ]:
# Question 23: Most Expensive Store
# Identify the store with the highest total operating cost.

Expensive =np.argmax(cost_data.sum(axis=1))
print(stores[Expensive])


Mumbai


In [ ]:
# Question 24: Lowest-Cost Store
# Identify the store with the lowest total cost.
min = np.argmin(cost_data.sum(axis=1))
print(stores[min])

Pune


In [ ]:
# Question 25: Most Expensive Product Category
# Determine which product category has the highest total cost across all stores.
index =np.argmax(cost_data.sum(axis=0))
print(categories[index])


Electronics


In [149]:
# Part 6: Profit Analysis Using Two Arrays
# Question 26: Profit Matrix
# Calculate the profit generated for every store and product category.

# Use:

# profit_data = sales_data - cost_data
# Display the complete profit matrix.

profit_data = sales_data - cost_data
print(profit_data)

[[210000 105000  90000  70000  65000  65000]
 [190000 110000  85000  85000  70000  70000]
 [220000  95000  95000  65000  65000  60000]
 [260000 120000 110000  95000  85000  85000]
 [160000  95000  75000  55000  60000  60000]]


In [ ]:
# Question 27: Store-Wise Profit
# Calculate the total profit generated by each store.
print("bengalore :",profit_data[0].sum())
print("hyderabad :", profit_data[1].sum())
print("chennai :", profit_data[2].sum())
print("mumbai :",profit_data[3].sum())
print("pune :",profit_data[4].sum())

bengalore : 605000
hyderabad : 610000
chennai : 600000
mumbai : 755000
pune : 505000


In [ ]:
# Question 28: Category-Wise Profit
# Calculate the total profit generated by each product category.
print("electronics :", profit_data[:, 0].sum())
print("groceries :", profit_data[:, 1].sum())
print("clothing :", profit_data[:,2].sum())
print("furniture :",profit_data[:,3].sum())
print("beauty :", profit_data[:,4].sum())
print("sports :",profit_data[:,5].sum())


electronics : 1040000
groceries : 525000
clothing : 455000
furniture : 370000
beauty : 345000
sports : 340000


In [ ]:
# Question 29: Most Profitable Store
# Identify the store that generated the highest total profit.

# Display:

# Store name
# Total sales
# Total cost
# Total profit

index=np.argmax(profit_data.sum(axis=1))
print("store;", stores[index])
print("total sales:",sales_data[index].sum())
print(cost_data[index].sum())
print(sales_data[index].sum()-cost_data[index].sum())

store; Mumbai
total sales: 2820000
2065000
755000


In [ ]:
# Question 30: Least Profitable Store
# Identify the store that generated the lowest total profit.

least = np.argmin(profit_data.sum(axis=1))
print("store: ", stores[least])

store:  Pune


In [ ]:
# Question 31: Most Profitable Category
# Find the category with the highest total profit across all stores.
index = np.argmax(profit_data.sum(axis=0))
print("category: ",categories[index])

category:  Electronics


In [ ]:
# Question 32: Least Profitable Category
# Find the category with the lowest total profit.

lesat=np.argmin(profit_data.sum(axis=0))
print("category: ",categories[lesat])

category:  Sports


In [ ]:
# Question 33: Maximum Individual Profit
# Find the highest profit generated by any single store-category combination.

# Display:

# Profit amount
# Store name
# Product category
# Use np.unravel_index().
index= np.argmax(profit_data)
r , c = np.unravel_index(index, profit_data.shape)
print("profit:",profit_data[r,c])
print("store:",stores[r])
print("category:", categories[c])


profit: 260000
store: Mumbai
category: Electronics


In [ ]:
# Question 34: Minimum Individual Profit
# Find the smallest profit generated by a store-category combination.

# Display the corresponding store and category.
index= np.argmin(profit_data)
r,c = np.unravel_index(index, profit_data.shape)
print("profit:",profit_data[r,c])
print("store:",stores[r])
print("category:", categories[c])

profit: 55000
store: Pune
category: Furniture


In [151]:
# Part 7: Profit Margin Analysis
# Question 35: Profit Margin Matrix
# Calculate the profit margin percentage for every store-category combination.

# Use:

# profit_margin = (profit_data / sales_data) * 100
# Round the result to two decimal places.
profit_margin = (profit_data / sales_data) * 100
print(profit_margin.round(2))

[[24.71 25.   29.03 25.45 34.21 28.89]
 [24.36 23.91 28.81 27.42 33.33 29.17]
 [23.91 24.36 27.94 25.   35.14 27.91]
 [24.76 23.53 29.33 27.54 34.   29.31]
 [23.19 23.46 26.79 24.44 34.29 29.27]]


In [ ]:
# Question 36: Store-Wise Profit Margin
# Calculate the overall profit margin percentage for each store using:

# Store Profit Margin =
# Total Store Profit / Total Store Sales × 100
store_profit_margin = (profit_data.sum(axis=1)/sales_data.sum(axis=1))*100
print(store_profit_margin.round(2))


[26.65 26.58 25.97 26.77 25.51]


In [4]:
# Question 37: Category-Wise Profit Margin
# Calculate the overall profit margin percentage for each product category.

category_profit_margin=(profit_data.sum(axis=0)/sales_data.sum(axis=0))*100
print(category_profit_margin.round(2))

[24.24 24.03 28.44 26.15 34.16 28.94]


In [ ]:
# Question 38: Best Store by Profit Margin
# Identify the store with the highest overall profit margin.
index = np.argmax(store_profit_margin)
print("store:",stores[index])

store: Mumbai


In [ ]:
# Question 39: Best Category by Profit Margin
# Identify the product category with the highest profit margin.
index=np.argmax(category_profit_margin)
print("category:",categories[index])

category: Beauty


In [ ]:
# Question 40: Low-Margin Transactions
# Management considers a profit margin below 22% to be weak.

# Find all store-category combinations where the profit margin is below 22%.

# Display:

# Store
# Category
# Sales
# Cost
# Profit
# Profit margin
# Use Boolean indexing.
low = profit_margin < 22
r,c = np.where(low)
for r,c in zip(r,c):
  print("store:",stores[r])
  print("category:",categories[c])
  print("sales:",sales_data[r,c])
  print("cost:",cost_data[r,c])
  print("profit:",profit_data[r,c])
  print("profit margin:",profit_margin[r,c])

In [ ]:
# Part 8: Boolean Filtering
# Question 41: High Sales Values
# Find all sales values greater than ₹5,00,000.

high=sales_data[sales_data> 500000]
print(high)

[ 850000  780000  920000 1050000  510000  690000]


In [ ]:
# Question 42: Low Sales Values
# Find all sales values below ₹2,00,000.
low = sales_data[sales_data<200000]
print(low)

[190000 185000 175000]


In [ ]:
# Question 43: High Profit Values
# Find all store-category combinations where profit is greater than ₹1,50,000.

high =profit_data[profit_data>150000]
print(high)

[210000 190000 220000 260000 160000]


In [ ]:
# Question 44: Moderate Sales Range
# Find sales values between ₹2,50,000 and ₹5,00,000.
# Use np.logical_and().

moderate=sales_data[np.logical_and(sales_data>= 250000,sales_data<=500000) ]
print(moderate)

[420000 310000 275000 460000 295000 310000 390000 340000 260000 375000
 345000 250000 290000 405000 280000]


In [ ]:
# Question 45: Premium Performance
# A store-category combination is considered premium when:

# Sales are greater than ₹5,00,000
# Profit is greater than ₹1,50,000
# Find all premium-performing combinations.
premium=profit_data[np.logical_and(sales_data>500000,profit_data>150000)]
print(premium)

[210000 190000 220000 260000 160000]


In [12]:
# Question 46: Underperforming Combinations
# A store-category combination is considered underperforming when:
# Sales are below ₹2,50,000
# Profit margin is below 25%
# Find all such combinations.

under = profit_margin[np.logical_and(sales_data<250000,profit_margin<25)]
print(under)

[24.44444444]


In [13]:
# Question 47: Category Performance Classification
# Create a new array that classifies every sales value as:

# "High" when sales are at least ₹5,00,000
# "Medium" when sales are between ₹2,50,000 and ₹4,99,999
# "Low" when sales are below ₹2,50,000
# Use np.where() or np.select().

conditions= [sales_data>= 500000,sales_data>=250000]
c = ["high", "medium"]
classi = np.select(conditions, c, default="low")
print(classi)

[['high' 'medium' 'medium' 'medium' 'low' 'low']
 ['high' 'medium' 'medium' 'medium' 'low' 'low']
 ['high' 'medium' 'medium' 'medium' 'low' 'low']
 ['high' 'high' 'medium' 'medium' 'medium' 'medium']
 ['high' 'medium' 'medium' 'low' 'low' 'low']]


In [4]:
# Part 9: Target-Based Analysis
# Use the following category-wise monthly sales targets:

sales_targets = np.array([
    800000,  # Electronics
    450000,  # Groceries
    320000,  # Clothing
    300000,  # Furniture
    200000,  # Beauty
    230000   # Sports
])

In [24]:
# Question 48: Target Comparison
# Compare every store’s category sales against sales_targets.

# Use NumPy broadcasting.
target = sales_data - sales_targets
print(target)

[[  50000  -30000  -10000  -25000  -10000   -5000]
 [ -20000   10000  -25000   10000   10000   10000]
 [ 120000  -60000   20000  -40000  -15000  -15000]
 [ 250000   60000   55000   45000   50000   60000]
 [-110000  -45000  -40000  -75000  -25000  -25000]]


In [32]:
# Question 49: Target Achievement Matrix
# Create a Boolean array where:

# True means the store achieved the category target
# False means the store failed to achieve the target
target_martix = sales_data >= sales_targets
print(target_martix)

[[ True False False False False False]
 [False  True False  True  True  True]
 [ True False  True False False False]
 [ True  True  True  True  True  True]
 [False False False False False False]]


In [41]:
# Question 50: Target Achievement Count
# Calculate the number of categories in which each store achieved its target.

target_count =np.sum(target_martix, axis=1)
print(target_count)

[1 4 2 6 0]


In [45]:
# Question 51: Best Target-Performing Store
# Find the store that achieved the highest number of category targets.

index=np.argmax(target_count)
print(stores[index])

Mumbai


In [50]:
# Question 52: Target Achievement by Category
# Calculate how many stores achieved the target for each product category.
target_count =np.sum(target_martix, axis=0)
print(target_count)

[3 2 2 2 2 2]


In [57]:
# Question 53: Sales Target Variance
# Calculate the difference between actual sales and target sales for every store.
# Use:
# Variance = Actual Sales - Target Sales
variance =sales_data-sales_targets
print(variance)

[[  50000  -30000  -10000  -25000  -10000   -5000]
 [ -20000   10000  -25000   10000   10000   10000]
 [ 120000  -60000   20000  -40000  -15000  -15000]
 [ 250000   60000   55000   45000   50000   60000]
 [-110000  -45000  -40000  -75000  -25000  -25000]]


In [63]:
# Question 54: Percentage Above or Below Target
# Calculate the percentage variance from the target using:

# Percentage Variance =
# (Actual Sales - Target Sales) / Target Sales × 100

percentage = (sales_data-sales_targets)/sales_targets*100
print(percentage)

[[  6.25        -6.66666667  -3.125       -8.33333333  -5.
   -2.17391304]
 [ -2.5          2.22222222  -7.8125       3.33333333   5.
    4.34782609]
 [ 15.         -13.33333333   6.25       -13.33333333  -7.5
   -6.52173913]
 [ 31.25        13.33333333  17.1875      15.          25.
   26.08695652]
 [-13.75       -10.         -12.5        -25.         -12.5
  -10.86956522]]


In [69]:
# Question 55: Stores Missing Electronics Target
# Identify stores that failed to achieve the Electronics sales target.
electronics_target = sales_targets[0]
result = stores[sales_data[:, 0] < electronics_target]
print(result)

['Hyderabad' 'Pune']


In [76]:
# Question 56: Stores Achieving All Targets
# Check whether any store achieved its target in all six product categories.
# Use np.all().

all= np.all(target_martix, axis=1)
print(stores[all])


['Mumbai']


In [83]:
# Question 57: Stores Achieving At Least One Target
# Identify stores that achieved at least one category target.
# Use np.any().
x = np.any(target_martix, axis=1)
print(stores[x])

['Bengaluru' 'Hyderabad' 'Chennai' 'Mumbai']


In [5]:
# Part 10: Discount Scenario
# SmartMart plans to offer category-wise discounts:

discount_rates = np.array([
    0.10,  # Electronics: 10%
    0.05,  # Groceries: 5%
    0.15,  # Clothing: 15%
    0.12,  # Furniture: 12%
    0.08,  # Beauty: 8%
    0.10   # Sports: 10%
])

In [7]:
# Question 58: Discount Amount Matrix
# Calculate the discount amount for each store-category combination.
# Use broadcasting.
dis=sales_data*discount_rates
print(dis)

[[ 85000.  21000.  46500.  33000.  15200.  22500.]
 [ 78000.  23000.  44250.  37200.  16800.  24000.]
 [ 92000.  19500.  51000.  31200.  14800.  21500.]
 [105000.  25500.  56250.  41400.  20000.  29000.]
 [ 69000.  20250.  42000.  27000.  14000.  20500.]]


In [10]:
# Question 59: Sales After Discount
# Calculate the net sales value after applying the category-wise discounts.
after_dis = sales_data - dis
print(after_dis)

[[765000. 399000. 263500. 242000. 174800. 202500.]
 [702000. 437000. 250750. 272800. 193200. 216000.]
 [828000. 370500. 289000. 228800. 170200. 193500.]
 [945000. 484500. 318750. 303600. 230000. 261000.]
 [621000. 384750. 238000. 198000. 161000. 184500.]]


In [17]:
# Question 60: Profit After Discount
#  Assuming costs remain unchanged, calculate the new profit after the discounts are applied.
profit =after_dis-cost_data
print(profit)

[[125000.  84000.  43500.  37000.  49800.  42500.]
 [112000.  87000.  40750.  47800.  53200.  46000.]
 [128000.  75500.  44000.  33800.  50200.  38500.]
 [155000.  94500.  53750.  53600.  65000.  56000.]
 [ 91000.  74750.  33000.  28000.  46000.  39500.]]


In [22]:
# Question 61: Profit Margin After Discount
# Calculate the new profit margin after applying discounts.
profit_margin=(profit/after_dis)*100
print(profit_margin)

[[16.33986928 21.05263158 16.5085389  15.2892562  28.48970252 20.98765432]
 [15.95441595 19.90846682 16.25124626 17.52199413 27.53623188 21.2962963 ]
 [15.4589372  20.37786775 15.22491349 14.77272727 29.4947121  19.89664083]
 [16.4021164  19.50464396 16.8627451  17.65480896 28.26086957 21.4559387 ]
 [14.65378422 19.42820013 13.86554622 14.14141414 28.57142857 21.40921409]]


In [27]:
# Question 62: Loss-Making Transactions
# Check whether any store-category combination becomes loss-making after discounts.

# Display the affected store and category names.
loss= profit<0
row, col=np.where(loss)
for row, col in zip(row, col):
  print("store:",stores[row])
  print("category:",categories[col])


In [34]:
# Question 63: Discount Impact
# Calculate how much total revenue the company loses because of the proposed discounts.
print(dis.sum())

1146350.0


In [38]:
# Question 64: Store Most Affected by Discounts
# Identify the store that loses the highest amount of revenue due to discounts.

print(stores[np.argmax(dis.sum(axis=1))])


Mumbai


In [46]:
# Part 11: Tax and Price Adjustment
# The government introduces category-wise tax rates:

tax_rates = np.array([
    0.18,
    0.05,
    0.12,
    0.18,
    0.18,
    0.12
])

In [7]:
# Question 65: Tax Collection Matrix
# Calculate the tax collected on sales for each store and category.
tax = sales_data*tax_rates
print(tax)

[[153000.  21000.  37200.  49500.  34200.  27000.]
 [140400.  23000.  35400.  55800.  37800.  28800.]
 [165600.  19500.  40800.  46800.  33300.  25800.]
 [189000.  25500.  45000.  62100.  45000.  34800.]
 [124200.  20250.  33600.  40500.  31500.  24600.]]


In [10]:
# Question 66: Sales Including Tax
# Calculate the final customer billing value after adding tax.
sales= sales_data+tax
print(sales)

[[1003000.  441000.  347200.  324500.  224200.  252000.]
 [ 920400.  483000.  330400.  365800.  247800.  268800.]
 [1085600.  409500.  380800.  306800.  218300.  240800.]
 [1239000.  535500.  420000.  407100.  295000.  324800.]
 [ 814200.  425250.  313600.  265500.  206500.  229600.]]


In [13]:
# Question 67: Store-Wise Tax Collection
# Calculate the total tax collected by each store.
tax_store=tax.sum(axis=1)
print(tax_store)

[321900. 321200. 331800. 401400. 274650.]


In [20]:
# Question 68: Category-Wise Tax Collection
# Calculate total tax collected for each category.
tax_category= tax.sum(axis=0)
print(tax_category)

[772200. 109250. 192000. 254700. 181800. 141000.]


In [25]:
# Question 69: Highest Tax-Contributing Store
# Identify the store that contributes the highest tax amount.
print(stores[np.argmax(tax_store)])

Mumbai


In [30]:
# Part 12: Array Modification
# Question 70: Updated Pune Electronics Sales
# The Pune store reports that its Electronics sales were entered incorrectly.

# Update Pune Electronics sales from ₹6,90,000 to ₹7,40,000.

# Make the change in a copied array without modifying the original array.

sales = sales_data.copy()
sales[4, 0] = 740000
print(sales)

[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 740000  405000  280000  225000  175000  205000]]


In [37]:
# Question 71: Revised Beauty Cost
# Due to supplier negotiations, Beauty product costs are reduced by 8% for all stores.

# Create an updated cost array.
cost = cost_data.copy()
cost[:,4] = cost[:,4]*0.92
print(cost)

[[640000 315000 220000 205000 115000 160000]
 [590000 350000 210000 225000 128800 170000]
 [700000 295000 245000 195000 110400 155000]
 [790000 390000 265000 250000 151800 205000]
 [530000 310000 205000 170000 105800 145000]]


In [49]:
# Question 72: Furniture Cost Increase
# Furniture costs increase by 12% for all stores.

# Update only the Furniture column.
cost = cost_data.copy()
cost[:,3] = cost[:,3]*1.12
print(cost)

[[640000 315000 220000 229600 125000 160000]
 [590000 350000 210000 252000 140000 170000]
 [700000 295000 245000 218400 120000 155000]
 [790000 390000 265000 280000 165000 205000]
 [530000 310000 205000 190400 115000 145000]]


In [55]:
# Question 73: Store Closure Simulation
# Assume the Pune store is temporarily closed.

# Remove Pune’s sales and cost data from the analysis using np.delete().
sales_store = np.delete(sales_data,4,axis = 0)
cost_store= np.delete(cost_data,4,axis = 0)
print(sales_store)
print(cost_store)
store_new = np.delete(store)


[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]]
[[640000 315000 220000 205000 125000 160000]
 [590000 350000 210000 225000 140000 170000]
 [700000 295000 245000 195000 120000 155000]
 [790000 390000 265000 250000 165000 205000]]


In [62]:
# Question 74: Adding a New Store
# A new Delhi store is opened with the following data:

# delhi_sales = np.array([
#     880000, 475000, 330000, 290000, 215000, 250000
# ])

# delhi_cost = np.array([
#     665000, 360000, 235000, 215000, 145000, 180000
# ])
# Add Delhi to both arrays using np.vstack().

# Also add "Delhi" to the stores array.

delhi_sales = np.array([
    880000, 475000, 330000, 290000, 215000, 250000
])

delhi_cost = np.array([
    665000, 360000, 235000, 215000, 145000, 180000
])
sales1 = np.vstack((sales_data,delhi_sales))
cost1 = np.vstack((cost_data,delhi_cost))
stores1 = np.append(stores, "Delhi")
print(sales1)
print(cost1)
print(stores1)

[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]
 [ 880000  475000  330000  290000  215000  250000]]
[[640000 315000 220000 205000 125000 160000]
 [590000 350000 210000 225000 140000 170000]
 [700000 295000 245000 195000 120000 155000]
 [790000 390000 265000 250000 165000 205000]
 [530000 310000 205000 170000 115000 145000]
 [665000 360000 235000 215000 145000 180000]]
['Bengaluru' 'Hyderabad' 'Chennai' 'Mumbai' 'Pune' 'Delhi']


In [72]:

# Question 75: Adding a New Product Category
# SmartMart starts selling Home Appliances.

# home_appliance_sales = np.array([
#     360000,
#     325000,
#     390000,
#     420000,
#     295000
# ])

# home_appliance_cost = np.array([
#     265000,
#     240000,
#     285000,
#     305000,
#     225000
# ])
# Add the new category as a column using np.column_stack() or np.hstack().
home_appliance_sales = np.array([
    360000,
    325000,
    390000,
    420000,
    295000
])

home_appliance_cost = np.array([
    265000,
    240000,
    285000,
    305000,
    225000
])
sales2 = np.column_stack((sales_data,  home_appliance_sales))
cost2= np.column_stack((cost_data,home_appliance_cost))
categories1=np.append(categories,"Home Appliances")
print(sales2)
print(cost2)
print(categories1)

[[ 850000  420000  310000  275000  190000  225000  360000]
 [ 780000  460000  295000  310000  210000  240000  325000]
 [ 920000  390000  340000  260000  185000  215000  390000]
 [1050000  510000  375000  345000  250000  290000  420000]
 [ 690000  405000  280000  225000  175000  205000  295000]]
[[640000 315000 220000 205000 125000 160000 265000]
 [590000 350000 210000 225000 140000 170000 240000]
 [700000 295000 245000 195000 120000 155000 285000]
 [790000 390000 265000 250000 165000 205000 305000]
 [530000 310000 205000 170000 115000 145000 225000]]
['Electronics' 'Groceries' 'Clothing' 'Furniture' 'Beauty' 'Sports'
 'Home Appliances']


In [82]:
# Part 13: Sorting and Ranking
# Question 76: Sort Stores by Sales
# Sort stores in ascending order based on total sales.

# Display store names and sales totals.

total= sales_data.sum(axis= 1)
index= np.argsort(total)
for i in index:
  print(stores[i],total[i])

Pune 1980000
Bengaluru 2270000
Hyderabad 2295000
Chennai 2310000
Mumbai 2820000


In [92]:
# Question 78: Sort Categories by Revenue
# Sort product categories from highest to lowest total revenue.
total_revenue=sales_data.sum(axis=0)
index =np.argsort(total_revenue)[::-1]
for i in index:
  print(categories[i],total_revenue[i])

Electronics 4290000
Groceries 2185000
Clothing 1600000
Furniture 1415000
Sports 1175000
Beauty 1010000


In [100]:
# Question 79: Top Three Store-Category Sales
# Find the three highest individual sales values in the complete sales matrix.

# Display their:

# Sales value
# Store name
# Category name

ind=np.argsort(sales_data.ravel())[-3:][::-1]
for i in index:
  row, col=  np.unravel_index(i, sales_data.shape)
  print("sales: ",sales_data[row,col])
  print("store : ",stores[row])
  print("category: ",categories[col])

sales:  850000
store :  Bengaluru
category:  Electronics
sales:  420000
store :  Bengaluru
category:  Groceries
sales:  310000
store :  Bengaluru
category:  Clothing
sales:  275000
store :  Bengaluru
category:  Furniture
sales:  225000
store :  Bengaluru
category:  Sports
sales:  190000
store :  Bengaluru
category:  Beauty


In [106]:
# Question 80: Bottom Three Profits
# Find the three lowest profit values in the profit matrix.

ind = np.argsort(profit_data.ravel())[:3]
for i in index:
  row, col=  np.unravel_index(i, profit_data.shape)
  print("profit: ",profit_data[row,col])
  print("store : ",stores[row])
  print("category: ",categories[col])


profit:  210000
store :  Bengaluru
category:  Electronics
profit:  105000
store :  Bengaluru
category:  Groceries
profit:  90000
store :  Bengaluru
category:  Clothing
profit:  70000
store :  Bengaluru
category:  Furniture
profit:  65000
store :  Bengaluru
category:  Sports
profit:  65000
store :  Bengaluru
category:  Beauty


In [110]:
# Part 14: Statistical Analysis
# Question 81: Sales Statistics
# Calculate the following for the complete sales array:

# Minimum
# Maximum
# Mean
# Median
# Standard deviation
# Variance
# 25th percentile
# 50th percentile
# 75th percentile

print("minimum :", np.min(sales_data))
print("maximum: ",np.max(sales_data))
print("mean : ",np.mean(sales_data))
print("median :", np.median(sales_data))
print("25th percentile: ", np.percentile(sales_data,25))
print("50th percentile: ",np.percentile(sales_data,50))
print("75th percentile: ", np.percentile(sales_data,75))
print("100th percentile : ", np.percentile(sales_data,100))
print("standard deviation: ",np.std(sales_data))
print("variance: ", np.var(sales_data))

minimum : 175000
maximum:  1050000
mean :  389166.6666666667
median : 302500.0
25th percentile:  228750.0
50th percentile:  302500.0
75th percentile:  416250.0
100th percentile :  1050000.0
standard deviation:  230322.53954448793
variance:  53048472222.222206


In [117]:
# Question 82: Store-Wise Standard Deviation
# Calculate the sales standard deviation for every store.

# Use this value to determine which store has the most variation between product categories.

std= np.std(sales_data,axis=1)
print(std)
index= np.argmax(std)
print(stores[index])

[223059.53365762 194502.5706771  249265.58794453 271860.87128039
 177200.45146669]
Mumbai


In [123]:
# Question 83: Category-Wise Standard Deviation
# Determine which product category has the highest variation in sales across stores.

std= np.std(sales_data,axis=0)
print(std)
index= np.argmax(std)
print(categories[index])

[122539.78945632  43312.81565542  33911.64991563  41303.75285613
  26570.66051117  29832.86778035]
Electronics


In [130]:
# Question 84: Sales Above Company Average
# Calculate the company-wide average sales value.

# Count how many store-category sales values are above this average.
avg = np.mean(sales_data)
print("avg :", avg)
count =np.sum(sales_data>avg)
print(count)


avg : 389166.6666666667
10


In [133]:
# Part 15: Reshaping and Transformation
# Question 86: Flatten Sales Data
# Convert the two-dimensional sales array into a one-dimensional array using:

# flatten()
# ravel()
# Explain the difference between the two methods.

print("flatten :", sales_data.flatten())
print("ravel: " , sales_data.ravel())



flatten : [ 850000  420000  310000  275000  190000  225000  780000  460000  295000
  310000  210000  240000  920000  390000  340000  260000  185000  215000
 1050000  510000  375000  345000  250000  290000  690000  405000  280000
  225000  175000  205000]
ravel:  [ 850000  420000  310000  275000  190000  225000  780000  460000  295000
  310000  210000  240000  920000  390000  340000  260000  185000  215000
 1050000  510000  375000  345000  250000  290000  690000  405000  280000
  225000  175000  205000]


In [142]:
#   Question 87: Reshape Sales Data
# Reshape the 5 × 6 sales array into:

# 3 × 10
# 10 × 3
# 2 × 15
# 15 × 2
# Verify that no data is lost.
sale1 = sales_data.reshape(3,10)
sale2 = sales_data.reshape(10,3)
sale3 = sales_data.reshape(2,15)
sale4 = sales_data.reshape(15,2)
print(sale1)
print(sale2)
print(sale3)
print(sale4)

[[ 850000  420000  310000  275000  190000  225000  780000  460000  295000
   310000]
 [ 210000  240000  920000  390000  340000  260000  185000  215000 1050000
   510000]
 [ 375000  345000  250000  290000  690000  405000  280000  225000  175000
   205000]]
[[ 850000  420000  310000]
 [ 275000  190000  225000]
 [ 780000  460000  295000]
 [ 310000  210000  240000]
 [ 920000  390000  340000]
 [ 260000  185000  215000]
 [1050000  510000  375000]
 [ 345000  250000  290000]
 [ 690000  405000  280000]
 [ 225000  175000  205000]]
[[ 850000  420000  310000  275000  190000  225000  780000  460000  295000
   310000  210000  240000  920000  390000  340000]
 [ 260000  185000  215000 1050000  510000  375000  345000  250000  290000
   690000  405000  280000  225000  175000  205000]]
[[ 850000  420000]
 [ 310000  275000]
 [ 190000  225000]
 [ 780000  460000]
 [ 295000  310000]
 [ 210000  240000]
 [ 920000  390000]
 [ 340000  260000]
 [ 185000  215000]
 [1050000  510000]
 [ 375000  345000]
 [ 250000  29

In [143]:
print(sales_data.size)
print(sale1.size)
print(sale2.size)
print(sale3.size)
print(sale4.size)

30
30
30
30
30


In [151]:
# Question 88: Transpose Sales Data
# Transpose the sales array so that:

# Rows represent product categories
# Columns represent stores
# Display the new shape.
trsp = sales_data.T
print("transpose: ", trsp)
print(sales_data.shape)
print(trsp.shape)

transpose:  [[ 850000  780000  920000 1050000  690000]
 [ 420000  460000  390000  510000  405000]
 [ 310000  295000  340000  375000  280000]
 [ 275000  310000  260000  345000  225000]
 [ 190000  210000  185000  250000  175000]
 [ 225000  240000  215000  290000  205000]]
(5, 6)
(6, 5)


In [149]:
# Question 89: Combined Sales and Cost Array
# Stack sales_data and cost_data vertically.

# Display the resulting shape.
cmb = np.vstack((sales_data,cost_data))
print(cmb)
print(cmb.shape)

[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]
 [ 640000  315000  220000  205000  125000  160000]
 [ 590000  350000  210000  225000  140000  170000]
 [ 700000  295000  245000  195000  120000  155000]
 [ 790000  390000  265000  250000  165000  205000]
 [ 530000  310000  205000  170000  115000  145000]]
(10, 6)


In [157]:
# Question 90: Store-Level Combined Data
# Create a three-dimensional array where:

# First layer contains sales data
# Second layer contains cost data
# Use np.stack().

# Display the shape of the new array.

cmb1 = np.stack((sales_data,cost_data))
print(cmb1)
print(cmb1.shape)

[[[ 850000  420000  310000  275000  190000  225000]
  [ 780000  460000  295000  310000  210000  240000]
  [ 920000  390000  340000  260000  185000  215000]
  [1050000  510000  375000  345000  250000  290000]
  [ 690000  405000  280000  225000  175000  205000]]

 [[ 640000  315000  220000  205000  125000  160000]
  [ 590000  350000  210000  225000  140000  170000]
  [ 700000  295000  245000  195000  120000  155000]
  [ 790000  390000  265000  250000  165000  205000]
  [ 530000  310000  205000  170000  115000  145000]]]
(2, 5, 6)


In [25]:
# Part 16: Missing Data Scenario
# The company discovers that some sales values were not recorded.

sales_with_missing = np.array([
    [850000, 420000, np.nan, 275000, 190000, 225000],
    [780000, 460000, 295000, np.nan, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, np.nan, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, np.nan, 205000]
])



In [12]:
# Question 91: Missing Value Detection
# Find:

# Total number of missing values
# Location of missing values
# Stores and categories containing missing values

print(np.isnan(sales_with_missing).sum())
row, col =np.where(np.isnan(sales_with_missing))
print("loc : ", list(zip(row,col)))
for row , col in zip(row,col):
  print("store: ",stores[row])
  print("category: ", categories[col])

4
loc :  [(np.int64(0), np.int64(2)), (np.int64(1), np.int64(3)), (np.int64(3), np.int64(1)), (np.int64(4), np.int64(4))]
store:  Bengaluru
category:  Clothing
store:  Hyderabad
category:  Furniture
store:  Mumbai
category:  Groceries
store:  Pune
category:  Beauty


In [19]:
# Question 92: Replace Missing Values with Zero
# Replace all missing sales values with zero.
sales_with_missing =np.nan_to_num(sales_with_missing,nan =0)
print(sales_with_missing)

[[ 850000.  420000.       0.  275000.  190000.  225000.]
 [ 780000.  460000.  295000.       0.  210000.  240000.]
 [ 920000.  390000.  340000.  260000.  185000.  215000.]
 [1050000.       0.  375000.  345000.  250000.  290000.]
 [ 690000.  405000.  280000.  225000.       0.  205000.]]


In [30]:
# Question 93: Replace with Company Average
# Replace missing values with the overall average of available sales values.

# Use np.nanmean().
avg =np.nanmean(sales_with_missing)
sales_avg = sales_with_missing.copy()
sales_avg[np.isnan(sales_avg)] = avg
print(sales_avg)

[[ 850000.          420000.          398846.15384615  275000.
   190000.          225000.        ]
 [ 780000.          460000.          295000.          398846.15384615
   210000.          240000.        ]
 [ 920000.          390000.          340000.          260000.
   185000.          215000.        ]
 [1050000.          398846.15384615  375000.          345000.
   250000.          290000.        ]
 [ 690000.          405000.          280000.          225000.
   398846.15384615  205000.        ]]


In [37]:
# Question 94: Replace with Category Average
# Replace each missing value with the average sales value of its respective product category.

ctg_avg = np.nanmean(sales_with_missing,axis=0)
sales_ctg_avg= sales_with_missing.copy()
row, col =np.where(np.isnan(sales_ctg_avg))
sales_ctg_avg[row,col]= ctg_avg[col]
print(sales_ctg_avg)


[[ 850000.  420000.  322500.  275000.  190000.  225000.]
 [ 780000.  460000.  295000.  276250.  210000.  240000.]
 [ 920000.  390000.  340000.  260000.  185000.  215000.]
 [1050000.  418750.  375000.  345000.  250000.  290000.]
 [ 690000.  405000.  280000.  225000.  208750.  205000.]]


In [42]:
# Question 95: Missing Value Impact
# Compare total sales before and after replacing missing values with zero.
befor = np.nansum(sales_with_missing)
zero= np.nan_to_num(sales_with_missing)
after =zero.sum()
print(sales_with_missing)
print(b)
print(sales_zero)
print(after)


[[ 850000.  420000.      nan  275000.  190000.  225000.]
 [ 780000.  460000.  295000.      nan  210000.  240000.]
 [ 920000.  390000.  340000.  260000.  185000.  215000.]
 [1050000.      nan  375000.  345000.  250000.  290000.]
 [ 690000.  405000.  280000.  225000.      nan  205000.]]
10370000.0
[[ 850000.  420000.       0.  275000.  190000.  225000.]
 [ 780000.  460000.  295000.       0.  210000.  240000.]
 [ 920000.  390000.  340000.  260000.  185000.  215000.]
 [1050000.       0.  375000.  345000.  250000.  290000.]
 [ 690000.  405000.  280000.  225000.       0.  205000.]]
10370000.0


In [49]:
# Part 17: Conditional Business Decisions
# Question 96: Store Performance Labels
# Classify each store based on total sales:

# "Excellent": Total sales above ₹28,00,000
# "Good": Total sales between ₹24,00,000 and ₹28,00,000
# "Needs Improvement": Total sales below ₹24,00,000
# Use np.select().
total_sales = sales_data.sum(axis= 1)
cond = [total_sales>2800000, total_sales>=2400000]
c = ["Excellent","Good"]
perf = np.select(cond,c,default="Needs Improvement")
print(perf)

['Needs Improvement' 'Needs Improvement' 'Needs Improvement' 'Excellent'
 'Needs Improvement']


In [56]:
# Question 97: Profitability Classification
# Classify each store-category combination as:

# "Highly Profitable": Profit above ₹2,00,000
# "Profitable": Profit between ₹1,00,000 and ₹2,00,000
# "Low Profit": Profit below ₹1,00,000
# "Loss": Profit below zero

condt = [profit_data<0, profit_data>= 200000,profit_data>= 100000]
c = ["Loss","Highly Profitable","Profitable"]
prof = np.select(condt,c,default="Low Profit")
print(prof)


[['Highly Profitable' 'Profitable' 'Low Profit' 'Low Profit' 'Low Profit'
  'Low Profit']
 ['Profitable' 'Profitable' 'Low Profit' 'Low Profit' 'Low Profit'
  'Low Profit']
 ['Highly Profitable' 'Low Profit' 'Low Profit' 'Low Profit' 'Low Profit'
  'Low Profit']
 ['Highly Profitable' 'Profitable' 'Profitable' 'Low Profit' 'Low Profit'
  'Low Profit']
 ['Profitable' 'Low Profit' 'Low Profit' 'Low Profit' 'Low Profit'
  'Low Profit']]


In [58]:
# Question 98: Expansion Recommendation
# A store is eligible for expansion when:

# Total sales are above ₹25,00,000
# Total profit is above ₹7,00,000
# Overall profit margin is above 25%
# Identify eligible stores
t_sales = sales_data.sum(axis=1)
t_profit= profit_data.sum(axis=1)
margin= (t_profit/t_sales)*100
eligible = (t_sales>2500000) & (t_profit>700000) & (margin>25)
print(stores[eligible])


['Mumbai']


In [201]:
# Question 99: Category Promotion Recommendation
# A product category should receive additional promotion when:

# Average sales are below ₹3,00,000
# Profit margin is above 25%
# Identify the categories that satisfy these conditions.
cagtegory_avg = np.mean(sales_data,axis=0)
catg_profit = profit_data.sum(axis=0)
catg_sales= sales_data.sum(axis=0)
catg_margin = (catg_profit/catg_sales)*100
promotion = (cagtegory_avg<300000) & (catg_margin>25)
print(categories[promotion])

['Furniture' 'Beauty' 'Sports']


In [68]:
# Question 100: Cost Optimization Recommendation
# Find store-category combinations where:

# Cost is greater than ₹2,50,000
# Profit margin is below 25%
# These combinations should be reviewed for cost optimization.

cond = (cost_data>250000) & (catg_margin<25)
r, c = np.where(cond)
for r, c in zip(r,c):
  print(stores[r], categories[c])

Bengaluru Electronics
Bengaluru Groceries
Hyderabad Electronics
Hyderabad Groceries
Chennai Electronics
Chennai Groceries
Mumbai Electronics
Mumbai Groceries
Pune Electronics
Pune Groceries


In [69]:
# Part 18: Inventory Scenario
# Use the following inventory arrays:

opening_stock = np.array([
    [120, 450, 300, 90, 250, 180],
    [110, 500, 280, 100, 270, 200],
    [130, 420, 320, 85, 240, 170],
    [150, 550, 350, 120, 300, 220],
    [100, 400, 260, 75, 220, 160]
])

units_sold = np.array([
    [95, 380, 240, 65, 190, 140],
    [85, 420, 230, 75, 210, 155],
    [105, 350, 270, 60, 180, 130],
    [125, 470, 295, 90, 235, 175],
    [75, 330, 205, 55, 165, 120]
])

In [71]:
# Question 101: Closing Stock
# Calculate closing stock using:

# Closing Stock = Opening Stock - Units Sold

closing_stock= opening_stock-units_sold
print(closing_stock)

[[25 70 60 25 60 40]
 [25 80 50 25 60 45]
 [25 70 50 25 60 40]
 [25 80 55 30 65 45]
 [25 70 55 20 55 40]]


In [77]:
# Question 102: Low-Stock Identification
# Identify store-category combinations where closing stock is below 30 units.
row , col = np.where(closing_stock<30)
for row, col in zip(row,col):
  print(stores[row],categories[col],closing_stock[row, col])

Bengaluru Electronics 25
Bengaluru Furniture 25
Hyderabad Electronics 25
Hyderabad Furniture 25
Chennai Electronics 25
Chennai Furniture 25
Mumbai Electronics 25
Pune Electronics 25
Pune Furniture 20


In [78]:
# Question 103: Stock Availability Percentage
# Calculate the percentage of opening stock that remains unsold.
Availability = (closing_stock/opening_stock)*100
print(Availability)

[[20.83333333 15.55555556 20.         27.77777778 24.         22.22222222]
 [22.72727273 16.         17.85714286 25.         22.22222222 22.5       ]
 [19.23076923 16.66666667 15.625      29.41176471 25.         23.52941176]
 [16.66666667 14.54545455 15.71428571 25.         21.66666667 20.45454545]
 [25.         17.5        21.15384615 26.66666667 25.         25.        ]]


In [85]:
# Question 104: Fast-Moving Products
# A product is considered fast-moving when more than 80% of its opening stock has been sold.

# Identify fast-moving store-category combinations.

moving= units_sold/opening_stock>0.8
r, c = np.where(moving)
for r,c in zip(r,c):
  print(stores[r],categories[c])


Bengaluru Groceries
Hyderabad Groceries
Hyderabad Clothing
Chennai Electronics
Chennai Groceries
Chennai Clothing
Mumbai Electronics
Mumbai Groceries
Mumbai Clothing
Pune Groceries


In [86]:
# Question 105: Category-Wise Units Sold
# Calculate the total units sold for each product category.
unit = np.sum(units_sold,axis=0)
print(unit)

[ 485 1950 1240  345  980  720]


In [94]:
# Question 106: Store-Wise Units Sold
# Calculate total units sold by each store.
store_unit = np.sum(units_sold,axis=1)
print(store_unit)

[1110 1175 1095 1390  950]


In [99]:
# Question 107: Best Store by Unit Sales
# Identify the store that sold the highest total number of units.
best= np.argmax(store_unit)
print(stores[best])

Mumbai


In [100]:
# Question 108: Reorder Requirement
# A store should reorder a category when closing stock is below 25 units.

# Create a Boolean reorder matrix.
x = closing_stock<25
print(x)

[[False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False  True False False]]


In [104]:
# Question 109: Reorder Quantity
# Assume each category must maintain 100 units after reordering.

# Calculate reorder quantities only for combinations where closing stock is below 25.

# For all other combinations, return zero.

qty = np.where(closing_stock<25,100-closing_stock,0)
print(qty)

[[ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0 80  0  0]]


In [109]:
# Part 19: Advanced NumPy Questions
# Question 110: Cumulative Store Sales
# Calculate cumulative category sales for each store using np.cumsum().
cum_sales =np.cumsum(sales_data,axis=1)
print(cum_sales)

[[ 850000 1270000 1580000 1855000 2045000 2270000]
 [ 780000 1240000 1535000 1845000 2055000 2295000]
 [ 920000 1310000 1650000 1910000 2095000 2310000]
 [1050000 1560000 1935000 2280000 2530000 2820000]
 [ 690000 1095000 1375000 1600000 1775000 1980000]]


In [116]:
# Question 111: Cumulative Company Sales
# Flatten the sales array and calculate cumulative company sales.
cum_sales= np.cumsum(sales_data.flatten())
print(cum_sales)

[  850000  1270000  1580000  1855000  2045000  2270000  3050000  3510000
  3805000  4115000  4325000  4565000  5485000  5875000  6215000  6475000
  6660000  6875000  7925000  8435000  8810000  9155000  9405000  9695000
 10385000 10790000 11070000 11295000 11470000 11675000]


In [118]:
# Question 112: Sales Difference Between Categories
# Calculate the difference between consecutive category sales for each store using np.diff().
diff = np.diff(sales_data, axis =1)
print(diff)

[[-430000 -110000  -35000  -85000   35000]
 [-320000 -165000   15000 -100000   30000]
 [-530000  -50000  -80000  -75000   30000]
 [-540000 -135000  -30000  -95000   40000]
 [-285000 -125000  -55000  -50000   30000]]


In [124]:
# Question 113: Unique Sales Values
# Find all unique sales values in sales_data.

# Also count the frequency of each value.
unique, count =np.unique(sales_data,return_counts=True)
print(unique)
print(count)

[ 175000  185000  190000  205000  210000  215000  225000  240000  250000
  260000  275000  280000  290000  295000  310000  340000  345000  375000
  390000  405000  420000  460000  510000  690000  780000  850000  920000
 1050000]
[1 1 1 1 1 1 2 1 1 1 1 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1]


In [129]:
# Question 114: Search for Specific Sales
# Check whether the value ₹4,20,000 exists in the sales array.

# Return its location.
row, column= np.where(sales_data == 420000)
print(row,column)

[0] [1]


In [133]:
# Question 115: Compare Sales and Cost
# Create a Boolean array showing whether sales are greater than cost for every combination.

# Verify whether all combinations are profitable using np.all().
profit =sales_data>cost_data
print(profit)
print(np.all(profit))

[[ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]]
True


In [136]:
# Question 116: Clip Profit Values
# For reporting purposes, management wants profit values limited to:

# Minimum: ₹75,000
# Maximum: ₹2,50,000
# Use np.clip() to create a reporting profit array.
x = np.clip(profit_data,75000,250000)
print(x)

[[210000 105000  90000  75000  75000  75000]
 [190000 110000  85000  85000  75000  75000]
 [220000  95000  95000  75000  75000  75000]
 [250000 120000 110000  95000  85000  85000]
 [160000  95000  75000  75000  75000  75000]]


In [140]:
# Question 117: Normalize Sales Data
# Normalize all sales values using min-max normalization:

# Normalized Sales =
# (Sales - Minimum Sales) / (Maximum Sales - Minimum Sales)
mini =np.min(sales_data)
maxi= np.max(sales_data)
norm=(sales_data-mini)/(maxi-mini)
print(norm)

[[0.77142857 0.28       0.15428571 0.11428571 0.01714286 0.05714286]
 [0.69142857 0.32571429 0.13714286 0.15428571 0.04       0.07428571]
 [0.85142857 0.24571429 0.18857143 0.09714286 0.01142857 0.04571429]
 [1.         0.38285714 0.22857143 0.19428571 0.08571429 0.13142857]
 [0.58857143 0.26285714 0.12       0.05714286 0.         0.03428571]]


In [146]:
# Question 118: Standardize Sales Data
# Standardize sales using:

# Standardized Sales =
# (Sales - Mean Sales) / Standard Deviationa
mean =np.mean(sales_data)
std=np.std(sales_data)
stand =(sales_data-mean)/std
print(stand)

[[ 2.00081735  0.13387024 -0.34372088 -0.49568169 -0.86472938 -0.71276857]
 [ 1.69689573  0.30753974 -0.40884695 -0.34372088 -0.77789463 -0.64764251]
 [ 2.30473897  0.00361811 -0.21346876 -0.56080776 -0.88643807 -0.75618594]
 [ 2.86916484  0.52462661 -0.06150795 -0.19176007 -0.60422513 -0.43055563]
 [ 1.30613936  0.06874418 -0.47397301 -0.71276857 -0.92985544 -0.79960332]]


In [155]:
# Question 119: Round Values
# Convert profit margin values into:

# Two decimal places
# Nearest whole number
# Floor values
# Ceiling values

print(np.round(profit_margin,2))
print(np.around(profit_margin))
print(np.floor(profit_margin))
print(np.ceil(profit_margin))


[[24.71 25.   29.03 25.45 34.21 28.89]
 [24.36 23.91 28.81 27.42 33.33 29.17]
 [23.91 24.36 27.94 25.   35.14 27.91]
 [24.76 23.53 29.33 27.54 34.   29.31]
 [23.19 23.46 26.79 24.44 34.29 29.27]]
[[25. 25. 29. 25. 34. 29.]
 [24. 24. 29. 27. 33. 29.]
 [24. 24. 28. 25. 35. 28.]
 [25. 24. 29. 28. 34. 29.]
 [23. 23. 27. 24. 34. 29.]]
[[24. 25. 29. 25. 34. 28.]
 [24. 23. 28. 27. 33. 29.]
 [23. 24. 27. 25. 35. 27.]
 [24. 23. 29. 27. 34. 29.]
 [23. 23. 26. 24. 34. 29.]]
[[25. 25. 30. 26. 35. 29.]
 [25. 24. 29. 28. 34. 30.]
 [24. 25. 28. 25. 36. 28.]
 [25. 24. 30. 28. 34. 30.]
 [24. 24. 27. 25. 35. 30.]]


In [160]:
# Question 120: Save and Load Data
# Save the following arrays as NumPy binary files:

# sales_data.npy
# cost_data.npy
# profit_data.npy
# Load them back and verify that the loaded arrays are equal to the original arrays.
np.save("sales_data.npy",sales_data)
np.save("cost_data.npy",cost_data)
np.save("profit_data.npy",profit_data)

sales_load= np.load("sales_data.npy")
print(np.array_equal(sales_data,sales_load))

cost_load =np.load("cost_data.npy")
print(np.array_equal(cost_data,cost_load))

profit_load= np.load("profit_data.npy")
print(np.array_equal(profit_data,profit_load))

True
True
True


In [209]:
# Part 20: Final Retail Analytics Project
# Prepare a complete NumPy-based retail performance report.

# Your report must contain the following information:

# Company Summary
# Total company sales
# Total company cost
# Total company profit
# Overall company profit margin
# Average transaction value
# Highest individual sales value
# Lowest individual sales value
# Store Summary
# For every store, display:

# Total sales
# Total cost
# Total profit
# Profit margin
# Number of category targets achieved
# Total units sold
# Expansion eligibility
# Category Summary
# For every category, display:

# Total sales
# Total cost
# Total profit
# Profit margin
# Average sales
# Number of stores achieving the target
# Total units sold
# Management Recommendations
# Based on the analysis, identify:

# Best-performing store
# Lowest-performing store
# Most profitable category
# Lowest-profit category
# Store recommended for expansion
# Category requiring additional marketing
# Store-category combinations needing cost optimization
# Store-category combinations requiring inventory reorder

print("            COMPANY SUMMARY                 ")
print("total sales: ", np.sum(sales_data))
print("total cost: ", np.sum(cost_data))
print("total profit : " ,np.sum(profit_data))
print("overall profit margin: ",np.round(np.mean(profit_margin),2))
print("average transaction value: ", np.round(np.mean(sales_data),2))
print("highest sales: ",np.max(sales_data))
print("lowest sales: ", np.min(sales_data))

print("                    STORE SUMMARY        ")
print("Store:", stores)
print("total sales: ", np.sum(sales_data,axis=1))
print("toal cost: ", np.sum(cost_data,axis=1))
print("total profit: ", np.sum(profit_data,axis=1))
print("profit margin: ", np.round(np.sum(profit_data, axis=1)/np.sum(sales_data, axis=1)*100,2))
print("targets achieved: ", np.sum(sales_data>250000,axis=1))
print("total units sold: ", np.sum(units_sold,axis=1))
store_sales = np.sum(sales_data,axis=1)
store_profit =np.sum(profit_data,axis=1)
store_margin= store_profit / store_sales * 100
expansion= ((store_sales>2500000)& (store_profit >700000)& (store_margin>25))
print("expansion eligibility: ",np.where(expansion, "eligible","not eigible"))

print("                CATEGORY SUMMARY              ")
print("best store: ", stores[np.argmax(store_sales)])
print("lowest store: ",stores[np.argmin(store_profit)])
category_profit = np.sum(profit_data, axis=0)
print("average sales:", np.round(np.mean(sales_data, axis=0), 2))
print("most profit category: ", categories[np.argmax(category_profit)])
print("lowest profit category: ", categories[np.argmin(category_profit)])
print("expansion: ", stores[expansion])
category_avg =np.mean(sales_data, axis=0)
category_margin=np.sum(profit_data, axis=0)/np.sum(sales_data, axis=0) * 100
print("additonal marketing: ",categories[(category_avg < 300000) & (category_margin > 25)])

row, col = np.where((cost_data>250000)&(profit_data/sales_data*100<25))
print("cost optimization: ")
for row, col in zip(row,col):
  print("store: ",stores[row],"category: ",categories[col])

r, c= np.where(closing_stock<25)
print("reorder: ")
for r, c in zip(r,c):
  print("store: ",stores[r],"category: ",categories[c])

            COMPANY SUMMARY                 
total sales:  11675000
total cost:  8600000
total profit :  3075000
overall profit margin:  27.62
average transaction value:  389166.67
highest sales:  1050000
lowest sales:  175000
                    STORE SUMMARY        
Store: ['Bengaluru' 'Hyderabad' 'Chennai' 'Mumbai' 'Pune']
total sales:  [2270000 2295000 2310000 2820000 1980000]
toal cost:  [1665000 1685000 1710000 2065000 1475000]
total profit:  [605000 610000 600000 755000 505000]
profit margin:  [26.65 26.58 25.97 26.77 25.51]
targets achieved:  [4 4 4 5 3]
total units sold:  [1110 1175 1095 1390  950]
expansion eligibility:  ['not eigible' 'not eigible' 'not eigible' 'eligible' 'not eigible']
                CATEGORY SUMMARY              
best store:  Mumbai
lowest store:  Pune
average sales: [858000. 437000. 320000. 283000. 202000. 235000.]
most profit category:  Electronics
lowest profit category:  Sports
expansion:  ['Mumbai']
additonal marketing:  ['Furniture' 'Beauty' 'Sport